# # Use the official MySQL image as the base
# FROM mysql:latest

# # Set the timezone
# ENV TZ=Asia/Seoul

# # Copy the initialization SQL script to the appropriate directory
# # COPY init.sql /docker-entrypoint-initdb.d/

# # Grant privileges during the image build
# RUN echo "GRANT ALL PRIVILEGES ON *.* TO '\${MYSQL_USERNAME}'@'%' IDENTIFIED BY '\${MYSQL_PASSWORD}' WITH GRANT OPTION;" > /docker-entrypoint-initdb.d/grant.sql
