version: "3.8"
services:
  front:
    container_name: "front-nuxt"
    build:
      context: .
      dockerfile: Dockerfile.front
    env_file:
      - ./.env
    ports:
      - "${FRONT_PORT}:3000"
    networks:
      - app_networks

  back:
    container_name: "back-nestjs"
    build:
      context: .
      dockerfile: Dockerfile.back
    env_file:
      - ./.env
    ports:
      - "${BACK_PORT}:3005"
    depends_on:
      - db
    networks:
      - data_networks
      - app_networks
    restart: unless-stopped

  db:
    container_name: "db-mysql"
    image: mysql:latest
    environment:
      - TZ=Europe/Paris
    env_file:
      - ./.env
    # ports:
    #   - "${DB_PORT}:3306"
    networks:
      - data_networks

networks:
  data_networks:
  app_networks:
